--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.3.56.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 5/14/2021 1:21:58 PM
-- Server version: 12.00.2269
-- Client version: 
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT [QLNH30-08].dbo.TRANGTHAI(matrangthai, tentrangthai, mota) VALUES (N'ACTIV', N'Active', N'Còn hoạt động, tồn tại hoặc làm việc')
INSERT [QLNH30-08].dbo.TRANGTHAI(matrangthai, tentrangthai, mota) VALUES (N'ELIMI', N'Eliminated', N'Ngừng hoàn toàn mọi hoạt động hoặc sự tồn tại')
INSERT [QLNH30-08].dbo.TRANGTHAI(matrangthai, tentrangthai, mota) VALUES (N'FREEZ', N'Freeze', N'Tạm ngưng hoạt động')
GO