--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.3.56.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 5/14/2021 1:21:57 PM
-- Server version: 12.00.2269
-- Client version: 
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT [QLNH30-08].dbo.QUYENHAN(MAQH, TENQH, MOTA, MACV) VALUES (N'QH001', N'THEM', N'Thêm nv , mo´n an , thu´c uô´ng, ba`n ,...', N'CVQL')
INSERT [QLNH30-08].dbo.QUYENHAN(MAQH, TENQH, MOTA, MACV) VALUES (N'QH002', N'SUA', N'Sua thong tin', N'CVQL')
INSERT [QLNH30-08].dbo.QUYENHAN(MAQH, TENQH, MOTA, MACV) VALUES (N'QH003', N'XOA', N'Xoa thong tin', N'CVQL')
GO