CREATE TABLE [dbo].[TONKHO] (
  [MAKHO] [varchar](5) NOT NULL,
  [MANGUYENLIEU] [varchar](5) NOT NULL,
  [MATHUCUONG] [varchar](5) NOT NULL,
  [SOLUONGTON] [float] NULL,
  CONSTRAINT [PK_TONKHO] PRIMARY KEY CLUSTERED ([MAKHO], [MANGUYENLIEU], [MATHUCUONG])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[TONKHO] WITH CHECK
  ADD CONSTRAINT [FK_TONKHO_KHO] FOREIGN KEY ([MAKHO]) REFERENCES [dbo].[KHO] ([MAKHO])
GO

ALTER TABLE [dbo].[TONKHO] WITH CHECK
  ADD CONSTRAINT [FK_TONKHO_NGUYENLIEU] FOREIGN KEY ([MANGUYENLIEU]) REFERENCES [dbo].[NGUYENLIEU] ([MANGUYENLIEU])
GO

ALTER TABLE [dbo].[TONKHO] WITH CHECK
  ADD CONSTRAINT [FK_TONKHO_THUCUONG] FOREIGN KEY ([MATHUCUONG]) REFERENCES [dbo].[THUCUONG] ([MATHUCUONG])
GO