CREATE TABLE [dbo].[HOADON] (
  [MAHD] [varchar](5) NOT NULL,
  [MAKH] [varchar](5) NULL,
  [MANV] [varchar](5) NULL,
  [NGAYLAP] [datetime] NULL,
  [NOIDUNG] [nvarchar](50) NULL,
  [HTTT] [nvarchar](20) NULL,
  [SOBAN] [varchar](5) NULL,
  [TINHTRANGHD] [nvarchar](20) NULL,
  [VAT] [float] NULL,
  [TIENSAUTHUE] [bigint] NULL,
  [TIENNHANKH] [bigint] NULL,
  [TIENTRALAIKH] [bigint] NULL,
  [makm] [varchar](5) NULL,
  CONSTRAINT [PK_HOADON] PRIMARY KEY NONCLUSTERED ([MAHD]),
  CONSTRAINT [FK_HOADON_BAN] FOREIGN KEY ([SOBAN]) REFERENCES [dbo].[BAN] ([SOBAN]),
  CONSTRAINT [Fk_hoadon_chuongtrinhkm] FOREIGN KEY ([makm]) REFERENCES [dbo].[CHUONGTRINHKM] ([MAKM]) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_HOADON_KH_HD_KHACHHAN] FOREIGN KEY ([MAKH]) REFERENCES [dbo].[KHACHHANG] ([MAKH]) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [FK_HOADON_NV_HD_NHANVIEN] FOREIGN KEY ([MANV]) REFERENCES [dbo].[NHANVIEN] ([MANV])
)
ON [PRIMARY]
GO

CREATE INDEX [KH_HD_FK]
  ON [dbo].[HOADON] ([MAKH])
  ON [PRIMARY]
GO

CREATE INDEX [NV_HD_FK]
  ON [dbo].[HOADON] ([MANV])
  ON [PRIMARY]
GO