CREATE TABLE [dbo].[CHUONGTRINHKM] (
  [MAKM] [varchar](5) NOT NULL,
  [MALOAIKM] [varchar](5) NULL,
  [TENKM] [nvarchar](100) NOT NULL,
  [NGAYBATDAU] [date] NOT NULL,
  [NGAYKETTHUC] [date] NOT NULL,
  [MOTA] [nvarchar](255) NULL,
  [DIEUKIENKM] [bigint] NULL,
  [TANGKEMMON] [varchar](5) NULL,
  CONSTRAINT [PK_CHUONGTRINHKM] PRIMARY KEY NONCLUSTERED ([MAKM]),
  CONSTRAINT [FK_CHUONGTR_LOAIKM_CT_LOAICTKM] FOREIGN KEY ([MALOAIKM]) REFERENCES [dbo].[LOAICTKM] ([MALOAIKM]) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [Fk_TANGKEMMON_MONAN] FOREIGN KEY ([TANGKEMMON]) REFERENCES [dbo].[MONAN] ([MAMON]) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT [Fk_TANGKEMMON_THUCUONG] FOREIGN KEY ([TANGKEMMON]) REFERENCES [dbo].[THUCUONG] ([MATHUCUONG])
)
ON [PRIMARY]
GO

CREATE INDEX [LOAIKM_CTKM_FK]
  ON [dbo].[CHUONGTRINHKM] ([MALOAIKM])
  ON [PRIMARY]
GO