CREATE TABLE [dbo].[BAN] (
  [SOBAN] [varchar](5) NOT NULL,
  [TENBAN] [varchar](10) NOT NULL,
  [TINHTRANGBAN] [varchar](10) NULL DEFAULT ('empty'),
  [MAKHUVUC] [varchar](5) NOT NULL,
  [matrangthai] [varchar](5) NULL,
  [NGAYXOABAN] [datetime] NULL,
  CONSTRAINT [PK_BAN1] PRIMARY KEY CLUSTERED ([SOBAN]),
  CONSTRAINT [FK_BAN_KHUVUC] FOREIGN KEY ([MAKHUVUC]) REFERENCES [dbo].[KHUVUC] ([MAKHUVUC]) ON DELETE CASCADE ON UPDATE CASCADE
)
ON [PRIMARY]
GO