CREATE TABLE [dbo].[CTHD_TU] (
  [MAHD] [varchar](5) NOT NULL,
  [MATHUCUONG] [varchar](5) NULL,
  [SOLUONG] [int] NULL,
  CONSTRAINT [FK_CTHD2_CTHD2_HOADON] FOREIGN KEY ([MAHD]) REFERENCES [dbo].[HOADON] ([MAHD]) ON DELETE CASCADE ON UPDATE CASCADE
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[CTHD_TU] WITH NOCHECK
  ADD CONSTRAINT [FK_CTHD2_THUCUONG] FOREIGN KEY ([MATHUCUONG]) REFERENCES [dbo].[THUCUONG] ([MATHUCUONG])
GO