CREATE TABLE [dbo].[NGUYENLIEU] (
  [MANGUYENLIEU] [varchar](5) NOT NULL,
  [TENNGUYENLIEU] [nvarchar](500) NULL,
  [MOTA] [nvarchar](300) NULL,
  [DVT] [nvarchar](50) NULL,
  CONSTRAINT [PK_NGUYENLIEU] PRIMARY KEY CLUSTERED ([MANGUYENLIEU])
)
ON [PRIMARY]
GO